services:
  - type: web
    name: ithaca-weather-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:server"
    envVars:
      - key: WEATHERAPI_KEY
        sync: false
